name: Build job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet msbuild -target:Restore ".\src\Project 1\Project1Solution.sln"
    - name: Build solution
      run: dotnet msbuild -property:Configuration=Release -restore:false ".\src\Project 1\Project1Solution.sln"
    - name: Test projects
      run: |
        dotnet build "src/Project 1/Project1Solution.sln" -c Release
        dotnet test "src/Project 1/Project1Solution.sln" --no-build --verbosity normal