name: .NET CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      Solution_Name: Project1Solution.sln # For now, only one solution
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true # Privacy preference
      DOTNET_NOLOGO: true # Personal preference
      SOLUTION_PATH: src/Project 1/Project1Solution.sln

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build project with release configuration
      run: dotnet build "${{ env.SOLUTION_PATH }}" --configuration Release

    - name: Test project (Currently unused)
      run: dotnet test "${{ env.SOLUTION_PATH }}" --configuration Release --no-build --verbosity normal
      continue-on-error: true  # No tests yet

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ github.sha }}
        path: |
          src/Project 1/**/bin/Release/net9.0/
          !src/Project 1/**/bin/Release/net9.0/ref/
        retention-days: 7
